// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Lap2_API.Models;

[Keyless]
[Table("DailyTransaction")]
public partial class DailyTransaction
{
    public int? id { get; set; }

    public int? val { get; set; }
}